<?php

return [
    "en" => [
        "name" => "Tiếng Anh",
        "name_by_language" => "English",
        "area" => "Toàn cầu",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "USD",
        "currency_code" => "$",
        "money_value" => "1",
        "decimal_places" => 2,
        "key" => "en",
        "latin"     => true,
        "flag_join_left_to_right" => false,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "phone-wallpapers",
        "data"      => [
            "home"          => "Home",
            "about_us"      => "About us",
            "event"             => "Event",
            "support"           => "Support",
            "connect_with_us"   => "Connect with us",
            "table_of_contents" => "Table of Contents",
            "photo_set"         => "Photo set",
            "share"             => "Share",
            "no_suitable_results_found" => "No suitable results found",
            "cart"              => "Cart",
            "your_cart_is_empty"    => "Your cart is empty",
            "continue_shopping"     => "Continue shopping",
            "full_set"          => "Full set",
            "image"             => "Image",
            "options"           => "Options",
            "product_guide_after_payment"   => "<div>After payment, you will receive the original image directly and via email for download and use.</div>",
            "suggestions_for_you"   => "Suggestions for you!",
            "each_image"        => "Each image",
            "each_set"          => "Each set",
            "propose" => "Propose",
            "favourite" => "Favourite",
            "newest" => "Newest",
            "oldest" => "Oldest",
            "browse_by" => "Browse by ",
            "sort_by" => "Sort by ",
            "filter_by" => "Filter by ",
            "filter_by_themes" => "Filter by Themes",
            "filter_by_styles" => "Filter by Styles",
            "filter_by_events" => "Filter by Events",
            "advanced_filter" => "Advanced Filter",
            "all" => "All",
            "added_to_cart" => "Added to Cart!",
            "view_cart" => "View Cart",
            "add_to_cart" => "Add to Cart",
            "buy_now" => "Buy Now",
            "undefined" => "Undefined",
            "total" => "Total",
            "remove_item_in_cart" => "Remove Item from Cart",
            "product_list" => "Product List",
            "product" => "Product",
            "unit_price" => "Unit Price",
            "total_price" => "Total Price",
            "payment" => "Payment",
            "information" => "Information",
            "email_prompt" => "If you enter your email, you will receive an additional copy for storage.",
            "email_receive" => "Email for receiving images",
            "payment_method" => "Payment Method",
            "fee" => "Fee",
            "payment_fee" => "Payment Fee",
            'view_all'  => 'View all',
            'login_name_com_vn' => 'Login Name.com.vn',
            'login_email' => 'Login Email',
            'password' => 'Password',
            'remember_me' => 'Remember me',
            'login' => 'Login',
            'or_login_with' => 'Or login with',
            'support' => 'Support',
            'download_guide' => 'Download Guide',
            'account_information' => 'Account Information',
            'my_downloads' => 'My Downloads',
            'logout' => 'Logout',
            'article' => "Article",
            'featured_articles' => 'Featured Articles',
            'news_category' => 'News Category',
            'payment_successful' => "Payment successful!",
            'thank_you_message' => "Thank you for supporting Name.com.vn. Your image is below, or you can check your email to download the image.",
            'order_id' => "Order ID",
            'email' => "Email",
            'click_to_download' => "Click to download",
            'step_1_buy_now' => "Step 1: Please enter your email.",
            'note_fill_email' => "* If you enter an email, an additional copy will be sent for storage.",
            'step_2_buy_now' => "Step 2: Choose a payment method.",
            'what_do_you_want_to_find_today' => "What do you want to find today?",
            'search' => "Search",
            /* xác nhận đơn hàng */
            'order_confirmation' => 'Order Confirmation',
            'thank_you_message_email' => 'Thank you for completing your order! Your wallpaper is ready to use.',
            'hello' => 'Hello',
            'purchase_date' => 'Purchase Date',
            'download_instructions' => 'You can download the wallpaper collection in the following ways:',
            'direct_download' => 'Direct download through the links below:',
            'sincerely' => 'Sincerely!',
            'login_instruction_message_email' => 'Or log in to <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> with your email and go to the <strong>"My Downloads"</strong> section.',
            'support_contact_message_email' => 'If you have any questions or need support, please contact us via email at <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => 'We wish you a great experience with your new wallpaper collection!',
            /* custom */
            "wallpaper_theme"  => [
                "liendoan"  => "Wallpaper Theme",
            ],
            "wallpaper_style"   => [
                "liendoan"  => "Wallpaper Style",
            ],
            "free_wallpaper"    => [
                "liendoan"  => "Free Wallpaper",
            ],
            "phone_wallpaper"         => [
                "liendoan"  => "Phone Wallpaper ",
            ],
            "product_description"   => [
                "liendoan"  => "<div>Transform your phone's wallpaper into a work of art with this stunning photo collection! Bring a fresh and unique style to your phone.</div>
                                <ul>
                                    <li>High resolution: 1440x3360, ensuring sharp images with every detail.</li>
                                    <li>Perfectly compatible with all types of phone screens.</li>
                                    <li>Easy and quick download in just a few simple steps.</li>
                                    <li>Usage rights included, feel free to share with your friends.</li>
                                </ul>
                                <div>Download now and experience the exciting difference on your phone's screen!</div>",
            ],
            "wallpaper_by_themes" => [
                "liendoan"  => "Wallpapers by Themes",
            ],
            "wallpaper_by_styles" => [
                "liendoan"  => "Wallpapers by Styles",
            ],
            "wallpaper_by_events" => [
                "liendoan"  => "Wallpapers by Events",
            ],
            "list_type_search" => [
                'liendoan' => [
                    'category_info' => 'Category',
                    'paid_wallpaper' => 'Paid Wallpapers',
                    'free_wallpaper' => 'Free Wallpapers',
                    'article' => 'Article',
                ],
            ],
            "copyright" => [
                "liendoan"  => "Copyright ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>. Designed and developed by Pham Van Phu. All rights reserved.",
            ]
        ]
    ],
    "vi" => [
        "name" => "Tiếng Việt",
        "name_by_language" => "Tiếng Việt",
        "area" => "Việt Nam",
        "scope" => "Ngôn ngữ khu vực châu Á",
        "currency" => "VND",
        "currency_code" => "đ",
        "money_value" => "25000",
        "decimal_places" => 0,
        "key" => "vi",
        "latin"     => true,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "hinh-nen-dien-thoai",
        "data"      => [
            "home"              => "Trang chủ",
            "about_us"          => "Về chúng tôi",
            "event"             => "Sự kiện",
            "support"           => "Hỗ trợ",
            "connect_with_us"   => "Kết nối với chúng tôi",
            "table_of_contents" => "Mục lục",
            "photo_set"         => "Bộ ảnh",
            "share"             => "Chia sẻ",
            "no_suitable_results_found" => "Không có kết quả phù hợp",
            "cart"              => "Giỏ hàng",
            "your_cart_is_empty"    => "Giỏ hàng của bạn trống",
            "continue_shopping" => "Tiếp tục mua sắm",
            "full_set"          => "Trọn bộ",
            "image"             => "Ảnh",
            "options"           => "Tùy chọn",
            "product_guide_after_payment"   => "<div>Sau khi thanh toán, Bạn sẽ nhận được ảnh gốc trực tiếp và qua mail để có thể tải xuống sử dụng.</div>",
            "suggestions_for_you"   => "Gợi ý cho bạn!",
            "each_image"        => "Từng ảnh",
            "each_set"          => "Từng bộ",
            "propose" => "Đề xuất",
            "favourite" => "Yêu thích",
            "newest" => "Mới nhất",
            "oldest" => "Cũ nhất",
            "browse_by" => "Duyệt theo ",
            "sort_by" => "Sắp xếp theo ",
            "filter_by" => "Lọc theo ",
            "filter_by_themes" => "Lọc theo Chủ Đề",
            "filter_by_styles" => "Lọc theo Phong Cách",
            "filter_by_events" => "Lọc theo Sự Kiện",
            "advanced_filter" => "Bộ lọc nâng cao",
            "all" => "Tất cả",
            "added_to_cart" => "Đã thêm vào giỏ hàng!",
            "view_cart" => "Xem Giỏ Hàng",
            "add_to_cart" => "Thêm Giỏ Hàng",
            "buy_now" => "Mua Ngay",
            "undefined" => "Không xác định",
            "total" => "Tổng",
            "remove_item_in_cart" => "Xóa sản phẩm trong Giỏ Hàng",
            "product_list" => "Danh sách Sản Phẩm",
            "product" => "Sản Phẩm",
            "unit_price" => "Đơn Giá",
            "total_price" => "Thành Tiền",
            "payment" => "Thanh Toán",
            "information" => "Thông Tin",
            "email_prompt" => "Nếu nhập Email bạn sẽ được gửi thêm một bản để lưu trữ.",
            "email_receive" => "Email dùng nhận ảnh",
            "payment_method" => "Hình thức Thanh Toán",
            "fee" => "Phí",
            "payment_fee" => "Phí thanh toán",
            'view_all' => 'Xem tất cả',
            'login_name_com_vn' => 'Đăng nhập Name.com.vn',
            'login_email' => 'Email đăng nhập',
            'password' => 'Mật khẩu',
            'remember_me' => 'Ghi nhớ tôi',
            'login' => 'Đăng nhập',
            'or_login_with' => 'Hoặc đăng nhập với',
            'support' => 'Hỗ trợ',
            'download_guide' => 'Hướng dẫn tải',
            'account_information' => 'Thông tin tài khoản',
            'my_downloads' => 'Tải xuống của tôi',
            'logout' => 'Đăng xuất',
            'article' => "Bài viết",
            'featured_articles' => 'Bài viết nổi bật',
            'news_category' => 'Chuyên mục tin tức',
            'payment_successful' => "Thanh toán thành công!",
            'thank_you_message' => "Cảm ơn bạn đã ủng hộ Name.com.vn. Hình ảnh của bạn ở phần bên dưới hoặc bạn có thể truy cập email của mình để tải ảnh.",
            'order_id' => "Mã đơn",
            'email' => "Email",
            'click_to_download' => "Nhấn để tải",
            'step_1_buy_now' => "Bước 1: Bạn vui lòng nhập email.",
            'note_fill_email' => "* Nếu nhập email bạn sẽ được gửi thêm một bản để lưu trữ.",
            'step_2_buy_now' => "Bước 2: Chọn hình thức thanh toán.",
            'what_do_you_want_to_find_today' => "Bạn muốn tìm gì hôm nay?",
            'search' => "Tìm kiếm",
            /* xác nhận đơn hàng */
            'order_confirmation' => 'Xác nhận đơn hàng',
            'thank_you_message_email' => 'Cảm ơn bạn đã hoàn tất đơn hàng của mình! Hình nền của bạn đã sẵn sàng để sử dụng.',
            'hello' => 'Xin chào',
            'purchase_date' => 'Ngày mua',
            'download_instructions' => 'Bạn có thể tải bộ hình nền bằng các cách sau:',
            'direct_download' => 'Tải trực tiếp qua các liên kết bên dưới:',
            'sincerely' => 'Trân trọng!',
            'login_instruction_message_email' => 'Hoặc đăng nhập vào <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> bằng email của bạn và vào phần <strong>"Tải xuống của tôi"</strong>',
            'support_contact_message_email' => 'Nếu có bất kỳ thắc mắc hoặc cần hỗ trợ, vui lòng liên hệ với chúng tôi qua email: <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => 'Chúc bạn có những trải nghiệm tuyệt vời cùng bộ sưu tập hình nền mới của mình!',
            /* custom */
            "wallpaper_theme"   => [
                "liendoan"  => "Chủ đề Hình Nền",
            ],
            "wallpaper_style"   => [
                "liendoan"  => "Phong cách Hình Nền",
            ],
            "free_wallpaper"    => [
                "liendoan"  => "Hình nền Miễn Phí",
            ],
            "phone_wallpaper"   => [
                "liendoan"  => "Hình nền điện thoại ",
            ],
            "product_description"   => [
                "liendoan"  => "<p>Biến màn hình nền điện thoại của bạn thành một tác phẩm nghệ thuật với bộ sưu tập ảnh tuyệt đẹp này! Đem lại phong cách mới lạ và sự tươi mới cho chiếc điện thoại của bạn.</p>
                                <ul>
                                    <li>Độ phân giải cao: 1440x3360, đảm bảo hình ảnh sắc nét đến từng chi tiết.</li>
                                    <li>Tương thích hoàn hảo với mọi loại màn hình điện thoại.</li>
                                    <li>Tải xuống dễ dàng và nhanh chóng chỉ với vài bước đơn giản.</li>
                                    <li>Đã bao gồm quyền sử dụng, bạn có thể thoải mái chia sẻ với bạn bè.</li>
                                </ul>
                                <div>Hãy tải ngay và cảm nhận sự khác biệt đầy thú vị trên màn hình điện thoại của bạn nhé!</div>
                            ",
            ],
            "wallpaper_by_themes" => [
                "liendoan"  => "Hình Nền Điện Thoại theo Chủ Đề",
            ],
            "wallpaper_by_styles" => [
                "liendoan"  => "Hình Nền Điện Thoại theo Phong Cách",
            ],
            "wallpaper_by_events" => [
                "liendoan"  => "Hình Nền Điện Thoại theo Sự Kiện",
            ],
            "list_type_search" => [
                'liendoan' => [
                    'category_info' => 'Danh mục',
                    'paid_wallpaper' => 'Hình nền trả phí',
                    'free_wallpaper' => 'Hình nền miễn phí',
                    'article' => 'Bài viết',
                ],
            ],
            "copyright" => [
                "liendoan"  => "Bản quyền ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>. Thiết kế và phát triển bởi Phạm Văn Phú. Mọi quyền được bảo lưu.",
            ]
        ]
    ],
];